notifications:
  email: false

language: node_js
node_js:
- '8'

cache:
  directories:
  - node_modules

# Testing
install:
- npm install
script:
- npm run eslint

# Deploy settings
addons:
  ssh_known_hosts: vacuumlabs.com

before_deploy:
- eval "$(ssh-agent -s)"
- ssh-add <( echo -e "$VACUUMLABS_UBUNTU" )
- ssh-add <( echo -e "$VACUUMLABS_OBEDBOT" )

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: production
